### ISSUE TITLE
work?

### ISSUE THREAD

**Issue by Driesboy** [ImagicalGamer/SkyWars#1]

**Comment by ImagicalGamer** [comment]
Yes it works, make a world with the name SkyWars and then do /save-all then do /save-off and then do /sw make SkyWars and setup your arena!

**Comment by ImagicalGamer** [comment]
It's not recommended to run on ImagicalMine or genisys yet but it does work on PocketMine. It will run in Gensisys but there will be some bugs.

**Comment by Driesboy** [comment]
i use only genisys

**Comment by ImagicalGamer** [comment]
Then it should work for you, the only known Genisys bugs are teleporting to the void after winning the game and PC clients can't always open chests.
